spring.application.name=todo_api

spring.datasource.url=jdbc:postgresql://localhost:5432/todo_db
spring.datasource.username=todo_user
spring.datasource.password=todo_pass
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

app.jwt.secret=CHANGE_ME_TO_A_LONG_RANDOM_SECRET_32_CHARS_MINIMUM
app.jwt.expiration-minutes=60

spring.h2.console.enabled=true
